kind: Service
apiVersion: v1
metadata:
  name: nginx
spec: 
  type: LoadBalancer
  selector: # lables are used as selectors
      app: nginx
      tier: frontend
      purpose: deployment
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80
      nodePort: {{ .values.service.nodePort }}